language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -y -qq python-numpy python-scipy python-matplotlib cython python-nose python-coverage
  - git clone git://github.com/pydata/pandas.git
  - cd pandas && python setup.py install
  - pip freeze
install:
  - python setup.py install
script: nosetests -v --with-coverage --cover-package=dtk
