language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
        - sudo apt-get install -y -qq python-setuptools python-numpy python-scipy python-matplotlib python-nose python-coverage
  - pip freeze
install:
  - python setup.py install
script: nosetests -v --with-coverage --cover-package=dtk
after_success: coveralls
