package:
  name: dynamicisttoolkit
  version: "0.4.0"

source:
  fn: DynamicistToolKit-0.4.0.tar.gz
  url: https://pypi.python.org/packages/source/D/DynamicistToolKit/DynamicistToolKit-0.4.0.tar.gz
  md5: d8d4c10a5ea76afa4372a478ab9d7d70

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

  run:
    - python
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

test:
  # Python imports
  imports:
    - dtk
    - dtk.test

about:
  home: http://github.com/moorepants/DynamicistToolKit
  license: UNLICENSE.txt
  summary: 'Various tools for theoretical and experimental dynamics.'
