package:
  name: dynamicisttoolkit
  version: "0.5.0"

source:
  fn: DynamicistToolKit-0.5.0.tar.gz
  url: https://pypi.python.org/packages/1e/ed/2be1322f723ef11f959581c7082100dd18b8b82107eca151a3730636290a/DynamicistToolKit-0.5.0.tar.gz
  md5: 4f4e1ef78c8560fb4e1be586b91df835

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

  run:
    - python
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

test:
  # Python imports
  imports:
    - dtk
    - dtk.test

about:
  home: http://github.com/moorepants/DynamicistToolKit
  license: UNLICENSE.txt
  summary: 'Various tools for theoretical and experimental dynamics.'
