package:
  name: dynamicisttoolkit
  version: "0.3.5"

source:
  fn: DynamicistToolKit-0.3.5.tar.gz
  url: https://pypi.python.org/packages/source/D/DynamicistToolKit/DynamicistToolKit-0.3.5.tar.gz
  md5: 84f9bbbbaf31b0c1da19cfe56f96cb60
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dynamicisttoolkit = dynamicisttoolkit:main
    #
    # Would create an entry point called dynamicisttoolkit that calls dynamicisttoolkit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

  run:
    - python
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

test:
  # Python imports
  imports:
    - dtk
    - dtk.test

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/moorepants/DynamicistToolKit
  license: UNLICENSE.txt
  summary: 'Various tools for theoretical and experimental dynamics.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
