package:
  name: dynamicisttoolkit
  version: "0.5.2"

source:
  fn: DynamicistToolKit-0.5.2.tar.gz
  url: https://files.pythonhosted.org/packages/86/8b/b9f1728e4f9c2c560f1650cbe957a461206f20102cb9e4505687799f0d2c/DynamicistToolKit-0.5.2.tar.gz
  sha256: 555cc1847c76b5775d9842360e4655d6fece371a7dab1f17e542867df3877b7b

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

  run:
    - python
    - numpy >=1.6.0
    - scipy >=0.9.0
    - matplotlib >=1.1.0

test:
  # Python imports
  imports:
    - dtk
    - dtk.test

about:
  home: http://github.com/moorepants/DynamicistToolKit
  license: UNLICENSE.txt
  summary: 'Various tools for theoretical and experimental dynamics.'
